version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    entrypoint: sh entrypoint.sh
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_user
      - POSTGRES_DB=django_db

volumes:
  postgres_data:
